import type { Metadata } from "next";
import { Sora, Inter, Road_Rage } from "next/font/google";
import "./globals.css";

const sora = Sora({
  variable: "--font-sora",
  display: "swap",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});
const roadRage = Road_Rage({
  variable: "--font-road-rage",
  display: "swap",
  subsets: ["latin"],
  weight: ["400"],
});

const inter = Inter({
  variable: "--font-inter",
  display: "swap",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${sora.variable} ${roadRage.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
